# add user specific settings
---
- name: add user to group
  become: yes
  command: "usermod -a -G microk8s {{ user }}"
  changed_when: true
  with_items: '{{ users }}'
  loop_control:
    loop_var: user
    label: '{{ user }}'

- name: Create .kube folder for the user
  become: yes
  become_user: '{{ user }}'
  file:
    path: ~/.kube
    state: directory
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: 0750
  with_items: '{{ users }}'
  loop_control:
    loop_var: user
    label: '{{ user }}'

- name: create kubectl config
  become: yes
  changed_when: true
  shell: microk8s config > /home/{{ user }}/.kube/config
  args:
    executable: /bin/bash
  with_items: '{{ users }}'
  loop_control:
    loop_var: user
    label: '{{ user }}'

- name: reaffirm permission on files
  become: yes
  file:
    path: ~/.kube
    state: directory
    owner: '{{ user }}'
    group: '{{ user }}'
    recurse: yes
  with_items: '{{ users }}'
  loop_control:
    loop_var: user
    label: '{{ user }}'

- name: add helm repository to user
  become: yes
  become_user: '{{ user }}'
  community.kubernetes.helm_repository:
    name: stable
    repo_url: https://charts.helm.sh/stable
  with_items: '{{ users }}'
  loop_control:
    loop_var: user
    label: '{{ user }}'
  when: microk8s_plugin_helm3_enable

- name: update helm repos
  become: yes
  become_user: '{{ user }}'
  community.kubernetes.helm:
    name: stable
    state: absent
    namespace: default
    update_repo_cache: yes
  with_items: '{{ users }}'
  loop_control:
    loop_var: user
    label: '{{ user }}'
  when: microk8s_plugin_helm3_enable
